### ISSUE TITLE
ConnectAccountOnboarding: Link bank account modal not working

### ISSUE THREAD

**Issue by ario1ir** [stripe/connect-js#113]
I'm trying to implement Stripe Connect embedded components. It works fine except for linking bank accounts. 
```

  <FullPageTakeOver open onClose={onClose}>
      <FullPageTakeOver.Header>
        <FullPageTakeOver.Header.Breadcrumbs items={['Stripe']} />
      </FullPageTakeOver.Header>
      <FullPageTakeOver.Content>
        <ConnectComponentsProvider connectInstance={stripeConnectInstance}>
          <ConnectAccountOnboarding onExit={onClose} />
        </ConnectComponentsProvider>
      </FullPageTakeOver.Content>
    </FullPageTakeOver>

```
![image](https://github.com/stripe/connect-js/assets/1414866/0e0df80e-6ed2-4436-bb76-f3ba75d30b6c)
iframe points to https://connect-js.stripe.com/stripejs_layer_035636d

f4864b1d3ac41.html#stripejs_layer_id=7e44be6b-8517-4619-[…]ent=stripe-connect-account-onboarding. 
 which is not loading the modal. 

`<iframe data-stripejs-layer="true" name="409de22f-464c-4b48-ab47-c66b2c353ee5" scrolling="no" src="https://connect-js.stripe.com/stripejs_layer_4402fc92c94b54f7cdaa.html#stripejs_layer_id=409de22f-464c-4b48-ab47-c66b2c353ee5&amp;embeddedComponent=stripe-connect-account-onboarding" style="position: fixed; height: 100%; width: 100%; top: 0px; left: 0px; background: transparent; border: 0px none; border-radius: 0px; box-sizing: content-box; cursor: auto; margin: 0px; max-height: none; max-width: none; opacity: 1; outline: none; padding: 0px; pointer-events: auto; transform: none; transition: none 0s ease 0s; user-select: auto; vertical-align: baseline; visibility: visible; overflow: hidden; z-index: 2147483647;"><html><head><title>Stripe JS</title><meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"><meta charset="utf-8"><script defer="defer" src="stripeJsLayer-42b7e0ca330628b2535c.js"></script></head><body><noscript>You need to enable JavaScript to run this app.</noscript></body></html></iframe>`

I expected to see this: 
![Screenshot 2024-04-17 at 2 35 40 PM](https://github.com/stripe/connect-js/assets/1414866/288a1db5-9efe-4399-9a7e-978dc03bce41)

**Comment by jorgea-stripe** [comment]
Can you share if there's anything specific about your setup? Are you using iframes yourself, or webviews by any chance?

I managed to get the flow to work in my test app:
<img width="735" alt="image" src="https://github.com/stripe/connect-js/assets/95381655/5cbde7d9-5e2e-4d8f-b9f7-5b827ba53215">

If you use https://furever.dev/ and sign up for an account there, can you repro the issue?

**Comment by ario1ir** [comment]
Yeah, I'm also able to see it on https://www.furever.dev/onboarding. I'm not using iframes or webviews. All the other onboarding pages are working fine. I don't see any console errors, but I just noticed that, compared to the Furever app, there is no network call to https://js.stripe.com/v3 in my app after 
https://connect-js.stripe.com/stripeJsLayer-f3a9ed6502b9cab5c1fe.js.

**Comment by ario1ir** [comment]
the issue was cause by quantum metrics script, closing this

**Comment by jorgea-stripe** [comment]
@ario1ir - could you share a bit more details here, I'd love to understand how the quantum metrics script interfered with our dialog!
