### ISSUE TITLE
Suggestion: ability to configure overlay background color for dark mode

### ISSUE THREAD

**Issue by emroot** [stripe/connect-js#114]
There's no way to configure the background color for the overlay at the moment, it works great in light mode, but in a dark mode site, because the value is always the same, it looks a funky.
### Light mode
<img width="1260" alt="image" src="https://github.com/stripe/connect-js/assets/110190/e27db5cd-0c0d-43bb-8f95-0765b985eb3e">

### Dark mode
<img width="1260" alt="image" src="https://github.com/stripe/connect-js/assets/110190/b6c64ce7-c3f0-4d30-9d70-578a780ea0c0">

**Comment by jojo-stripe** [comment]
Hey @emroot , you can actually use `colorBackground`  in AppearanceVariables to configure this. 

<img width="1192" alt="image" src="https://github.com/stripe/connect-js/assets/124314569/d9ffbf24-64e0-4d95-81e2-887ef5a8a5a2">

We have an interactive demo showcasing our theming variables here if you'd like to play around with it. https://docs.stripe.com/connect/customize-connect-embedded-components

**Comment by jojo-stripe** [comment]
Do you mean a separate variable just for the background color of the overlay? That's different from the background color of the other components?

**Comment by emroot** [comment]
Yeah just the background color for the overlay, because in dark mode it looks washed out.
Works great on light mode tho

**Comment by emroot** [comment]
@jojo-stripe did my comment made sense? any sense if this is something you will be supporting?

**Comment by kaiying-stripe** [comment]
@emroot we're planning to add a variable to enable customizing the background color in the near future.

**Comment by kaiying-stripe** [comment]
@emroot We added the new [variable](https://docs.stripe.com/connect/embedded-appearance-options) `overlayBackdropColor`, closing this now. FFT reopen if there's other issues related to this!

**Comment by emroot** [comment]
Amazing!! Thank you so much.
