### ISSUE TITLE
Funds Text

### ISSUE THREAD

**Issue by 0ctan33** [stripe/connect-js#121]
hey team!

Just a small issue, the text for available funds on the "See Details" modal is missing a space between daily and to.

<img width="409" alt="Screenshot 2024-06-15 150913" src="https://github.com/stripe/connect-js/assets/76810766/573d9fe4-802b-4f0f-a785-e79a8e0714bb">

**Comment by CatoriClothing** [comment]
Additionally when capturing a payment the successful text popup doesn't really relate to the capture. Currently 

Capture successful
"The funds from this payment have been authorized but not collected. You can capture the funds from the customer's card at any time."

but this is not the case. The funds have been collected once you've captured the funds so I think this should be updated to reflect that

**Comment by kaiying-stripe** [comment]
@0ctan33 Thanks for reporting! Both issues should be fixed now
