### ISSUE TITLE
Nuxt3 SSR

### ISSUE THREAD

**Issue by randomnessdev** [stripe/connect-js#146]
Hello,

How is it possible to use connect-js (loadConnectAndInitialize) with Nuxt3 (SSR) ? Is there a documentation forseen for this?

Thank you

**Comment by kaiying-stripe** [comment]
Hi, connect-js should work with SSR if you use loadConnectAndInitialize from @stripe/connect-js/pure. Our documentation has an example with Next.js: https://docs.stripe.com/connect/connect-embedded-components/quickstart?client=next
