### ISSUE TITLE
[bug] "Your session has expired. Please log in again to continue"

### ISSUE THREAD

**Issue by waltershewmake** [stripe/connect-js#157]
### Background
I am unsure whether this issue should be reported within this repo or https://github.com/stripe/react-connect-js, so I'm opening it here. 

I've encountered a potential bug within the Stripe Connect JS SDK collection. 

Once the onboarding component loads, it prompts the user to "Add Information." This is normal and expected. However, after clicking the button and signing in, a red "Your session has expired. Please log in again to continue" error message appears. This worked like yesterday, and all of the sudden it is no longer working.

![Screenshot 2024-09-07 at 7 06 16 PM](https://github.com/user-attachments/assets/7a57f969-3d30-44a1-8807-d5e349e4c579)

Looking at the network logs reveals the following response across three different requests:
```json
{
    "error": {
        "message": "Invalid API Key provided: em_test_*********************************************************************************************loaAo5",
        "type": "invalid_request_error"
    }
}
```

This API key issue is not in regard to my Stripe API keys, which begin with either `sk_test_` or `pk_test_`. I am not sure where this `em_test_` key is coming from but I'm assuming its something internal to either this library or https://github.com/stripe/react-connect-js.

### Reproduction
I have created a minimal reproduction which is available here: [https://github.com/waltershewmake/stripe-connect-js-session-bug](https://github.com/waltershewmake/stripe-connect-js-session-bug)

**Comment by Ferdidurke** [comment]
Have the same issue today

**Comment by jojo-stripe** [comment]
Hi @Ferdidurke and @waltershewmake, we were temporarily experiencing some issues on our Connect API endpoints. This issue should now be fixed, let me know if you're still seeing this error!
