### ISSUE TITLE
Static or compiled version for use with vanilla JS

### ISSUE THREAD

**Issue by medcelerate** [stripe/connect-js#163]
Correct me if I am wrong but I don't see any documentation for how to use this without NPM or a method to statically compile the JS for static serving? In our case we have an SSR application that uses vanilla JS with simple templates that load their JS from CDN or static. Is there a way to use this without NPM?

**Comment by michaelphines-stripe** [comment]
Hey @medcelerate, we do support that! Check out our docs here and feel free to follow up in this thread if you have any questions.

https://docs.corp.stripe.com/connect/get-started-connect-embedded-components#integrate-without-sdk
